# Header
menu:
  Home: /
  About me: /about-me
  Archives: /archives
  Tools: /tools
rss: /atom.xml
banner: images/banner.jpg
subtitle: Full Stack,DevOPS,Cloud Develop,Kubernetes,CDN, DNS, WAF,SRE,DevSecOps

# Content
excerpt_link: Read More
fancybox: true
recent_posts_limits: 5
# Footer
copyright: |-
  <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a></br>
  All website licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a></br>

# Sidebar
sidebar: right
widgets:
- category
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: G-Z7L6BT187M
favicon: /images/favicon.png
twitter: https://twitter.com/kongfaceworld

# Header links
# Each name must correspond to the icon name of Fork Awesome
# https://forkaweso.me/Fork-Awesome/icons/
links:
  github: https://github.com/nicelizhi
  twitter: https://twitter.com/kongfaceworld
#  telegram: https://t.me/your_telegram_account
