menu:
  home: / || fa fa-home
  about: /about-me/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  tools: /tools/ || fa fa-screwdriver-wrench
  sitemap: /sitemap.xml || fa fa-sitemap
#  commonweal: /404/ || fa fa-heartbeat