name: Daily RSS Feed Update

on:
  schedule:
    # every six hours run the job
    - cron: '0 */6 * * *'
    # muanlly trigger
  push:
    branches:
      - main
      # only py file changed
    paths:
      - 'rss2md.py'

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  update-rss-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          # 在这里添加你的脚本来安装依赖
          echo "Installing dependencies..."
          pip install -r requirements.txt
          echo "Dependencies installed!"

      - name: Fetch RSS feed and update site
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GOOGLE_AI_KEY: ${{ secrets.GOOGLE_AI_KEY }}
        run: |
          # 在这里添加你的脚本来获取 RSS feed 并更新站点
          echo "Fetching RSS feed and updating site..."
            # 例如，使用 curl 命令获取 RSS feed
            # 读取 Rss feed 的内容 生成 md 文件
            python3 rss2md.py
            # 生成 md 文件后，将其提交到仓库
            git add .
            git config --global user.email nice.lizhi@gmail.com
            git config --global user.name "xxl4"
            git commit -m "Update RSS feed"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/xxl4/me.git
            echo "RSS feed updated!"
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
  
      - name: Install Hexo and dependencies
        run: |
          npm install hexo-cli -g
          npm install
  
      - name: Generate and deploy Hexo site
        run: |
          hexo generate
          hexo deploy  

            