name: Daily RSS Feed Update

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-rss-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch RSS feed and update site
        run: |
          # 在这里添加你的脚本来获取 RSS feed 并更新站点
          echo "Fetching RSS feed and updating site..."
            # 例如，使用 curl 命令获取 RSS feed
          curl -s https://www.computerweekly.com/rss/IT-security.xml > It-security.xml
            # 读取 Rss feed 的内容 生成 md 文件
            python3 rss2md.py It-security.xml
            # 生成 md 文件后，将其提交到仓库
            git add .
            git commit -m "Update RSS feed"
            git push
            echo "RSS feed updated!"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            